### ISSUE TITLE
BP-2348 Move the "Test" folder outside of the "Src" folder.

### ISSUE THREAD

**Issue by avido** [buckaroo-it/BuckarooSDK_PHP#85]
Besides the fact I'd personally liked to see the "tests" outside the "src" folder, this probably is just a personal preference, but still.... 

It would be advisable to revise all the unit tests. As a lot of them don't make sense or aren't trustworthy (for instance [Buckarootest](https://github.com/buckaroo-it/BuckarooSDK_PHP/blob/master/src/Tests/Payments/BuckarooVoucherTest.php)  

```php
public function it_creates_a_buckaroo_payment()
    {
        $response = $this->buckaroo->method('buckaroovoucher')->pay(
            [
                'amountDebit' => '10',
                'invoice' => uniqid(),
                'vouchercode' => 'vouchercode',
            ]
        );

        $this->assertTrue($response->isFailed());
    }
```

In above test we're validation something we expect to be successful just to fail.

**Comment by ShuCh3n** [comment]
Dear @avido,

Great advice. We are planning to move the test outside of the src folder. 

About the unit test, we can only expect a successful response for some tests because every merchant account is differently configurated. So that is why we decided that we expect a failed response for some tests. As long the payload is valid, and we don't get any weird responses back then it is acceptable for now.

**Comment by avido** [comment]
Maybe have a look at https://docs.phpunit.de/en/9.5/test-doubles.html

**Comment by ShuCh3n** [comment]
Dear @avido 

Thanks that is helpful! We have created two tickets for these two requests.
